### ISSUE TITLE
AddTodo dispatch prop type

### ISSUE THREAD

**Issue by ghost** [devserkan/react-with-idiomatic-redux#1]
Hello,

Since I could not find a way to send you an email though I would open an issue. First of all, great work to make it working with router v4. There is only one thing, which I am sure is basic, that I don't understand.

In AddTodo.js how does the dispatch property get passed on to the AddTodo???? I would have expected to see a property assignment in App.js but I can't find how this is working. I am sure this has to do with the ES6 magic but still I don't understand....

const AddTodo = ( { dispatch } ) => {

So I would appreciate if you could enlighten me!

Thanks!

**Comment by ghost** [comment]
Well, sounds like I had to read over again the same things but now I understand it....

[https://github.com/reactjs/react-redux/blob/master/docs/api.md#provider-store](url)
mapDispatchToProps(dispatch, [ownProps]): dispatchProps] (Object or Function): If an object is passed, each function inside it is assumed to be a Redux action creator. An object with the same function names, but with every action creator wrapped into a dispatch call so they may be invoked directly, will be merged into the component’s props.

If a function is passed, it will be given dispatch as the first parameter. It’s up to you to return an object that somehow uses dispatch to bind action creators in your own way. (Tip: you may use the bindActionCreators() helper from Redux.)

If your mapDispatchToProps function is declared as taking two parameters, it will be called with dispatch as the first parameter and the props passed to the connected component as the second parameter, and will be re-invoked whenever the connected component receives new props. (The second parameter is normally referred to as ownProps by convention.)

**_If you do not supply your own mapDispatchToProps function or object full of action creators, the default mapDispatchToProps implementation just injects dispatch into your component’s props._**

Again, thanks for providing the great code sample. It helped me a lot!!!

**Comment by devserkan** [comment]
I am sorry for seeing this issue after a year later! Shame on me, I did not watch my own repo :) I realized this repo's issues while I'm playing with another project and surprised :) Glad that you solved it and thank you for sharing your understandings. Believe me, digging it yourself and understanding how things work is the best way of learning and you did it very well.

**Comment by devserkan** [comment]
Test

**Comment by devserkan** [comment]
Test2

**Comment by devserkan** [comment]
Test3

**Comment by devserkan** [comment]
Test4

**Comment by devserkan** [comment]
Test5

**Comment by devserkan** [comment]
Test

**Comment by devserkan** [comment]
test5

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test6

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test5

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test5

**Comment by devserkan** [comment]
test6

**Comment by devserkan** [comment]
test7

**Comment by devserkan** [comment]
test8

**Comment by devserkan** [comment]
test9

**Comment by devserkan** [comment]
test10

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test5

**Comment by devserkan** [comment]
test6

**Comment by devserkan** [comment]
lklk

**Comment by devserkan** [comment]
jjhjhj

**Comment by devserkan** [comment]
test9

**Comment by devserkan** [comment]
ppopopo

**Comment by devserkan** [comment]
test10

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test5

**Comment by devserkan** [comment]
test6

**Comment by devserkan** [comment]
test7

**Comment by devserkan** [comment]
test8

**Comment by devserkan** [comment]
test9

**Comment by devserkan** [comment]
test10

**Comment by devserkan** [comment]
test11

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test5

**Comment by devserkan** [comment]
test6

**Comment by devserkan** [comment]
test7

**Comment by devserkan** [comment]
tets1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test4

**Comment by devserkan** [comment]
test6

**Comment by devserkan** [comment]
test7

**Comment by devserkan** [comment]
test8

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
Test22

**Comment by devserkan** [comment]
teeest

**Comment by devserkan** [comment]
test1

**Comment by devserkan** [comment]
test2

**Comment by devserkan** [comment]
test3

**Comment by devserkan** [comment]
test
