### ISSUE TITLE
reducers called three times for each action dispatch

### ISSUE THREAD

**Issue by macsdragon** [devserkan/react-with-idiomatic-redux#2]
First of all thanks for sharing this. That is very helpful!
I noticed that for each action dispatched (and logged in the redux logger) the corresponding reducer  function gets called 3 times. for instance when one of the filter links is clicked the ids reducer function is called three times with action type FETCH_TODOS_REQUEST and then three times with action type FETCH_TODOS_SUCCESS. Also each reducer function gets called three times with each of the initial action types redux/PROBE_UNKNOWN_ACTION and redux/INIT. That does not seem right.

**Comment by macsdragon** [comment]
I think the problem was me and my (lack) of understanding about the call sequence of redux on the reducers. I realised that all reducer functions are aways called after dispatching an action. this explains the above. 

`const listByFilter = combineReducers({
         all: createList('all'),
         active: createList('active'),
         completed: createList('completed')
});`

since all three reducers are called by a single dispatch, createList's ids is called three times

**Comment by devserkan** [comment]
I am sorry for seeing this issue so late. Shame on me, I did not watch my own repo :) I realized this repo's issues while I'm playing with another project and surprised :)  I'm glad that you solved the problem and share it with us.
